apiVersion: apps/v1
kind: Deployment
metadata:
  name: permafrost-frontend
  namespace: permafrost
  labels:
    app.kubernetes.io/name: permafrost
    app.kubernetes.io/component: frontend
    app.kubernetes.io/version: "1.0.0"
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: permafrost
      app.kubernetes.io/component: frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: permafrost
        app.kubernetes.io/component: frontend
        app.kubernetes.io/version: "1.0.0"
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
      containers:
      - name: frontend
        image: permafrost-frontend:1.0.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: permafrost-config
              key: NODE_ENV
        - name: NEXT_PUBLIC_API_URL
          value: "https://api.permafrost.yourdomain.com"
        - name: NEXT_PUBLIC_AZURE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: azure-ad-secrets
              key: NEXT_PUBLIC_AZURE_CLIENT_ID
        - name: NEXT_PUBLIC_AZURE_TENANT_ID
          valueFrom:
            secretKeyRef:
              name: azure-ad-secrets
              key: NEXT_PUBLIC_AZURE_TENANT_ID
        - name: NEXT_PUBLIC_AZURE_REDIRECT_URI
          valueFrom:
            secretKeyRef:
              name: azure-ad-secrets
              key: NEXT_PUBLIC_AZURE_REDIRECT_URI
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: nextjs-cache
          mountPath: /.next
      volumes:
      - name: tmp
        emptyDir: {}
      - name: nextjs-cache
        emptyDir: {}
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: permafrost-frontend
  namespace: permafrost
  labels:
    app.kubernetes.io/name: permafrost
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: permafrost
    app.kubernetes.io/component: frontend
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: permafrost-frontend-hpa
  namespace: permafrost
  labels:
    app.kubernetes.io/name: permafrost
    app.kubernetes.io/component: frontend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: permafrost-frontend
  minReplicas: 2
  maxReplicas: 8
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 60
