apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nats-pvc
  namespace: permafrost
  labels:
    app.kubernetes.io/name: permafrost
    app.kubernetes.io/component: messaging
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: fast-ssd
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nats-config
  namespace: permafrost
  labels:
    app.kubernetes.io/name: permafrost
    app.kubernetes.io/component: messaging
data:
  nats.conf: |
    # NATS Server Configuration
    port: 4222
    http_port: 8222
    
    # JetStream configuration
    jetstream {
      store_dir: "/data/jetstream"
      max_memory_store: 1GB
      max_file_store: 10GB
    }
    
    # Logging
    log_file: "/dev/stdout"
    logtime: true
    debug: false
    trace: false
    
    # Limits
    max_connections: 1000
    max_control_line: 4096
    max_payload: 1048576
    max_pending: 67108864
    
    # Authentication (optional)
    # authorization {
    #   users = [
    #     {user: "permafrost", password: "secure_password"}
    #   ]
    # }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: permafrost-nats
  namespace: permafrost
  labels:
    app.kubernetes.io/name: permafrost
    app.kubernetes.io/component: messaging
    app.kubernetes.io/version: "2.10.14"
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: permafrost
      app.kubernetes.io/component: messaging
  template:
    metadata:
      labels:
        app.kubernetes.io/name: permafrost
        app.kubernetes.io/component: messaging
        app.kubernetes.io/version: "2.10.14"
    spec:
      securityContext:
        fsGroup: 1000
      containers:
      - name: nats
        image: nats:2.10.14-alpine
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 4222
          name: nats
        - containerPort: 8222
          name: monitor
        args:
        - "--config"
        - "/etc/nats/nats.conf"
        volumeMounts:
        - name: nats-config
          mountPath: /etc/nats
        - name: nats-storage
          mountPath: /data
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 1Gi
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8222
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8222
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
      volumes:
      - name: nats-config
        configMap:
          name: nats-config
      - name: nats-storage
        persistentVolumeClaim:
          claimName: nats-pvc
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: permafrost-nats
  namespace: permafrost
  labels:
    app.kubernetes.io/name: permafrost
    app.kubernetes.io/component: messaging
spec:
  type: ClusterIP
  ports:
  - port: 4222
    targetPort: 4222
    protocol: TCP
    name: nats
  - port: 8222
    targetPort: 8222
    protocol: TCP
    name: monitor
  selector:
    app.kubernetes.io/name: permafrost
    app.kubernetes.io/component: messaging
